# Generated by Django 3.2 on 2022-08-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
