# Generated by Django 3.2 on 2022-08-11 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productview',
            name='quantity',
        ),
    ]
